"""Domain enums used across the SmartDesk AI schema."""

from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    AGENT = "AGENT"
    CUSTOMER = "CUSTOMER"


class TicketStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_CUSTOMER = "WAITING_CUSTOMER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class TicketPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class TicketSource(str, Enum):
    WEB = "WEB"
    EMAIL = "EMAIL"
    CHAT = "CHAT"
    PHONE = "PHONE"
    API = "API"


class ArticleStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class NotificationType(str, Enum):
    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_REASSIGNED = "TICKET_REASSIGNED"
    TICKET_COMMENT = "TICKET_COMMENT"
    TICKET_RESOLVED = "TICKET_RESOLVED"
    TICKET_REOPENED = "TICKET_REOPENED"
    TICKET_UPDATED = "TICKET_UPDATED"
    SLA_WARNING = "SLA_WARNING"
    SLA_BREACHED = "SLA_BREACHED"
    MENTION = "MENTION"

class TicketEventType(str, Enum):
    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"
    TICKET_ASSIGNED = "TICKET_ASSIGNED"
    TICKET_REASSIGNED = "TICKET_REASSIGNED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    COMMENT_ADDED = "COMMENT_ADDED"
    TICKET_RESOLVED = "TICKET_RESOLVED"
    TICKET_REOPENED = "TICKET_REOPENED"
    TICKET_CLOSED = "TICKET_CLOSED"
    SLA_POLICY_APPLIED = "SLA_POLICY_APPLIED"
    SLA_BREACHED = "SLA_BREACHED"

class AIOperation(str, Enum):
    CLASSIFY = "CLASSIFY"
    SUGGEST_PRIORITY = "SUGGEST_PRIORITY"
    SUMMARIZE = "SUMMARIZE"
    SUGGEST_RESPONSE = "SUGGEST_RESPONSE"
    SUGGEST_NEXT_ACTION = "SUGGEST_NEXT_ACTION"


class AIJobStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"


class AISuggestionKind(str, Enum):
    CLASSIFICATION = "CLASSIFICATION"
    PRIORITY = "PRIORITY"
    SUMMARY = "SUMMARY"
    SUGGESTED_RESPONSE = "SUGGESTED_RESPONSE"
    NEXT_ACTION = "NEXT_ACTION"


class AISuggestionStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"